name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements/dev-requirements.txt
      - name: Build notebooks
        run: |
          make build
      - name: Run tests
        run: |
          make check
