name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'
      - uses: astral-sh/setup-uv@v5
      - name: Install dependencies
        run: uv pip sync requirements/requirements-dev.txt
      - name: Build notebooks
        run: |
          make build
      - name: Run tests
        run: |
          make check
