name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements/requirements-dev.txt

      - name: Build notebooks
        run: |
          make build

      - name: Run tests
        run: |
          make check

      - uses: mamba-org/setup-micromamba@v1

      - name: Build voici site
        run: |
          make site

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: voici-site
          path: site/

  pages:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: voici-site
          path: site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
          force_orphan: true
